a=input ("Name:")
b=input ("Age:")
c=input ("College Name:")
a=str (a)
b=int (b)
c=str (c)
print("my name is %s my age is %d my college name is %s" %(a,b,c))
print("Marks Obtained:")
SM=input("marks of simulation and modeling:")
AI=input("marks of artificial intelligence:")
CR=input("marks of cryptography:")
CN=input("marks of computer network:")
DAA=input("marks of design of data algorithm and analysis:")

SM=float(SM)
AI=float(AI)
CR=float(CR)
CN=float(CN)
DAA=float(DAA)
sum=SM+AI+CR+CN+DAA
print("The sum of your marks is: %2f" %(sum))