a=input ("Name:")
b=input ("Age:")
c=input ("College Name:")
a=str (a)
b=int (b)
c=str (c)
print("my name is %s my age is %s my college name is %s" %(a,b,c))
print("Marks Obtained:")
SM=input("marks of simulation and modeling:")
AI=input("marks of artificial intelligence:")
CR=input("marks of cryptography:")
CN=input("marks of computer network:")
DAA=input("marks of design of data algorithm and analysis:")

SM=int(SM)
AI=int(AI)
CR=int(CR)
CN=int(CN)
DAA=int(DAA)
sum=SM+AI+CR+CN+DAA
print("The sum of your marks is: %s" %(sum))